Snake can eat itself
mgandeva/Snake pull request #6
Opened 2024-01-19 09:41 UTC by eGreshkov

2024-01-22 11:58 UTC, mgandeva commented on src/app/models/snake.model.ts
> +        this.body = [grid.getCell(0, 7), grid.getCell(0,6), grid.getCell(0,5), grid.getCell(0,4), grid.getCell(0,3), grid.getCell(0,2), grid.getCell(0,1), grid.getCell(0,0), grid.getCell(1,0), grid.g
This was probably added only to verify that the solution works, so we should remove it

2024-01-22 22:31 UTC, stefania-tsvetkova requested changes

2024-01-22 22:31 UTC, stefania-tsvetkova commented on src/app/models/snake.model.ts
> +        if(tail.some(tailCell => tailCell === head))
Just `return tail.some(tailCell => tailCell === head)`

2024-01-22 22:31 UTC, stefania-tsvetkova commented on src/app/app.component.ts
> +    if(this.snake.hasEatenSelf()){
Just `return this.snake.hasEatenSelf()`

2024-02-08 13:34 UTC, mgandeva approved these changes

2025-03-19 09:18 UTC, closed without merging